name: MeetJoeBloke
favicon: null
layout_spectrum: 0.18435375299304724
typography_spectrum: 0.8606560435146093
title: MeetJoeBloke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.41658286517485976
  lightness: 0.17778399493545294
  saturation: 0.25
  rhythmicContrast: 0.05351501633413136
purpose: []
