name: MeetJoeBloke
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8606560435146093
title: MeetJoeBloke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72bcfd'
    - '#fdfdfd'
    - '#62a203'
    - '#fe0003'
    - '#001f19'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
